---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#############################
# Start the job on all push #
#############################
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
        with:
            fetch-depth: 0
            ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/checkout@v2
        if: github.event_name == 'push'
        with:
          fetch-depth: 0

      ############################################
      # Run Linter against Markdown in code base #
      ############################################
      - name: Lint Markdown
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_MARKDOWN: true
